version: "3.7"

services:
  learn-subtitles-backend:
    container_name: learn-subtitles-backend
    image: golang:1.18-alpine
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    networks:
      - learn-subtitles-network
    volumes:
      - ../learn-subtitles:/app
    working_dir: /app
    command: sh -c "go run cmd/learn-subtitles/main.go"

  learn-subtitles-master-postgres:
    container_name: learn-subtitles-master-postgres
    build:
      context: .
      dockerfile: .docker/postgresql/master/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .docker/postgresql/master/pgdata:/var/lib/postgresql/data
      - .docker/postgresql/master/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_MASTER_PORT}:${DB_MASTER_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PASSWORD} -d ${DB_NAME}" ]
      timeout: 45s
      interval: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    networks:
      - learn-subtitles-network

networks:
  learn-subtitles-network:
    name: learn-subtitles-network
    driver: bridge